// src/cmpStore/Video/vue/video.vue
<style lang="scss" scoped>
@import '../video.scss';
</style>
<template>
  <div class="cannonui-video">
    <video
      ref="rootRef"
      :muted="options.muted"
      :auto-play="options.autoplay"
      :loop="options.loop"
      :poster="options.poster"
      :controls="options.controls"
      :preload="options.preload"
    >
      <source
        :src="source"
        :type="type"
      />
    </video>
  </div>
</template>
<script lang="ts">
import createComponent from '@/utils/vue_component';
import {
  nextTick,
  onMounted,
  onUnmounted,
  reactive,
  ref,
  toRefs,
  watch
} from 'vue';
const { componentName, create } = createComponent('video');
export default create({
  props: {
    source: {
      type: String,
      default: ''
    },
    type: {
      type: String,
      default: ''
    },
    options: {
      type: Object,
      default: {
        autoplay: false,
        volume: 0.5,
        poster: '',
        loop: false,
        controls: true,
        muted: false,
        disabled: false,
        playsinline: false,
        touchPlay: false,
        preload: ''
      },
      required: true
    },
    model: {
      type: String,
      default: ''
    }
  },
  emits: ['click', 'play', 'pause', 'playend', 'ended', 'timeupdate'],
  setup(props, { emit }) {
    const rootRef = ref<HTMLVideoElement>();
    const state = reactive({
      curState: ''
    });
    const init = () => {
      if (props.options.autoplay) {
        nextTick(() => {
          rootRef.value?.play?.();
        });
      }

      if (props.options.playinline) {
        rootRef.value?.setAttribute('playinline', props.options.playinline);
        rootRef.value?.setAttribute(
          'webkit-playinline',
          props.options.playinline
        );
        rootRef.value?.setAttribute('x5-video-player-type', 'h5-page');
        rootRef.value?.setAttribute('x5-video-player-fullscreen', '');
      }

      rootRef.value?.addEventListener('play', play);
      rootRef.value?.addEventListener('pause', pause);
      rootRef.value?.addEventListener('timeupdate', timeupdate);
      rootRef.value?.addEventListener('ended', ended);
    };
    watch(
      () => props.source,
      (newVal) => {
        newVal &&
          nextTick(() => {
            rootRef.value?.load();
          });
      }
    );
    const play = () => {
      state.curState = 'play';
      emit('play', rootRef.value);
    };
    const pause = () => {
      state.curState = 'pause';
      emit('pause', rootRef.value);
    };
    const timeupdate = () => {
      state.curState = 'timeupdate';
      emit('timeupdate', rootRef.value);
    };
    const ended = () => {
      state.curState = 'ended';
      emit('ended', rootRef.value);
    };
    onMounted(() => init());
    onUnmounted(() => {
      rootRef.value?.removeEventListener('play', play);
      rootRef.value?.removeEventListener('ended', ended);
      rootRef.value?.removeEventListener('timeupdate', timeupdate);
      rootRef.value?.removeEventListener('pause', pause);
    });
    return {
      rootRef,
      ...toRefs(props)
    };
  }
});
</script>

// src/cmpStore/Video/react/video.tsx
//@ts-ignore
import React, { FunctionComponent, useEffect, useRef } from 'react';
import '../video.scss';

export interface VideoProps {
  source: {
    type: string;
    src: string;
  };
  options: {
    controls?: boolean;
    muted?: boolean;
    autoplay?: boolean;
    poster?: string;
    playsinline?: boolean;
    loop?: boolean;
  };
  className: string;
  style: React.CSSProperties;
  play: (e: HTMLVideoElement) => void;
  pause: (e: HTMLVideoElement) => void;
  playEnd: (e: HTMLVideoElement) => void;
  onPlayFuc: (e: HTMLVideoElement) => void;
  onPauseFuc: (e: HTMLVideoElement) => void;
  onPlayend: (e: HTMLVideoElement) => void;
}
const defaultProps = {
  source: {
    type: {},
    src: '',
  },
  options: {
    controls: true,
    muted: false,
    autoplay: false,
    poster: '',
    playsinline: false,
    loop: false,
  },
} as VideoProps;
export const Video: FunctionComponent<
  Partial<VideoProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const {
    children,
    source,
    options,
    className,
    play,
    pause,
    playEnd,
    onPlayFuc,
    onPauseFuc,
    onPlayend,
    ...restProps
  } = { ...defaultProps, ...props };
  const rootRef = useRef<HTMLVideoElement>(null);
  useEffect(() => {
    init();
  }, []);
  const init = () => {
    if (rootRef.current) {
      const videoRef = rootRef.current;
      if (options.autoplay) {
        setTimeout(() => {
          videoRef.play();
        }, 200);
      }
      if (options.playsinline) {
        videoRef.setAttribute('playsinline', String());
        videoRef.setAttribute(
          'webkit-playsinline',
          String(options.playsinline)
        );
        videoRef.setAttribute('x5-video-player-type', 'h5-page');
        videoRef.setAttribute('x5-video-player-fullscreen', 'false');
      }
      videoRef.addEventListener('play', () => {
        onPlayFuc && onPlayFuc(videoRef);
        play && play(videoRef);
      });
      videoRef.addEventListener('pause', () => {
        onPauseFuc && onPauseFuc(videoRef);
        pause && pause(videoRef);
      });
      videoRef.addEventListener('ended', () => {
        videoRef.currentTime = 0;
        onPlayend && onPlayend(videoRef);
        playEnd && playEnd(videoRef);
      });
    }
  };
  return (
    <div className="chihuoui-video">
      <video
        className="chihuoui-video-player"
        muted={options.muted}
        autoPlay={options.autoplay}
        loop={options.loop}
        poster={options.poster}
        controls={options.controls}
        ref={rootRef}
        src={source.src}
      >
        <source
          src={source.src}
          type={source.type}
        />
        <track kind="captions" />
      </video>
    </div>
  );
};

Video.defaultProps = defaultProps;
Video.displayName = 'ChihuouiVideo';
