// src/cmpStore/Table/vue/demo.vue
<style lang="scss" scoped>
@import '../table.scss';
</style>
<template>
  <Table
    :data="data1"
    :columns="column1"
  ></Table>
</template>
<script lang="ts">
import { reactive, toRefs } from 'vue';
import Table from './table.vue';
export default {
  props: {},
  emits: [],
  components: { Table },
  setup(props) {
    const sampleData = reactive({
      data1: [
        {
          name: 'Tom',
          age: 12
        },
        {
          name: 'Yi',
          age: 16
        }
      ],
      column1: [
        {
          key: 'name',
          title: '名字'
        },
        {
          key: 'age',
          title: '年龄'
        }
      ]
    });
    return {
      ...toRefs(sampleData)
    };
  }
};
</script>

// src/cmpStore/Table/react/demo.tsx
import React, { useState } from 'react';
import { Table } from './table';

const TableDemo = () => {
  const [column1, setColumn1] = useState([
    {
      title: '姓名',
      key: 'name',
    },
    {
      title: '年龄',
      key: 'age',
    },
  ]);

  const [data1, setData1] = useState([
    {
      name: 'Tom',
      age: 10,
    },
    {
      name: 'Hi',
      age: 12,
    },
    {
      name: '小张',
      age: 16,
    },
  ]);
  return (
    <>
      <div className="demo">
        <h2>基础用法</h2>
        <Table columns={column1} data={data1}></Table>
      </div>
    </>
  );
};

export default TableDemo;
