// src/cmpStore/Switch/react/switch.tsx
//@ts-ignore
import React, { useState, useEffect, FunctionComponent } from 'react';
import '../switch.scss';

export interface SwitchProps {
  isAsync: boolean;
  checked: boolean;
  disable: boolean;
  activeColor: string;
  inactiveColor: string;
  activeText: string;
  inactiveText: string;
  className: string;
  style: React.CSSProperties;
  onChange: (val: boolean, event: React.MouseEvent) => void;
}
const defaultProps = {
  active: false,
  checked: false,
  isAsync: false,
  activeColor: '#fa2c19',
  inactiveColor: '#ebebeb',
  activeText: '',
  inactiveText: '',
  className: '',
} as SwitchProps;
export const Switch: FunctionComponent<
  Partial<SwitchProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const {
    isAsync,
    checked,
    disable,
    activeColor,
    inactiveColor,
    activeText,
    inactiveText,
    onChange,
    className,
    style,
    children,
  } = { ...defaultProps, ...props };

  const [value, setValue] = useState(checked);
  const classes = () => `
    ${`chihuoui-switch`} ${value ? 'switch-open' : 'switch-close'} ${
    disable ? 'chihuoui-switch-disable' : ''
  } ${`chihuoui-switch-base`} ${className}
  `;
  const getStyles = () => {
    return {
      backgroundColor: value ? activeColor : inactiveColor,
      ...(style || {}),
    };
  };
  const onClick = (e: any) => {
    if (disable) {
      return;
    }
    if (!isAsync) {
      setValue(!value);
    }
    onChange && onChange(!value, e);
  };
  useEffect(() => {
    setValue(checked);
  }, [checked]);
  return (
    <div
      onClick={(e) => onClick(e)}
      style={getStyles()}
      className={classes()}
    >
      <div className="switch-button">
        {!value && <div className="close-line" />}
        {activeText && (
          <>
            {value ? (
              <div className={`chihuoui-switch-label open`}>{activeText}</div>
            ) : (
              <div className={`chihuoui-switch-label close`}>
                {inactiveText}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

Switch.defaultProps = defaultProps;
Switch.displayName = 'ChihuouiSwitch';

// src/cmpStore/Switch/vue/switch.vue
<template>
  <view @click="onClick" :style="getStyles" :class="classes">
    <view class="switch-button">
      <!-- <view v-show="!modelValue" class="close-line"></view> -->
      <template v-if="activeText">
        <view v-show="modelValue" class="chihuoui-switch-label open">{{activeText}}</view>
        <view v-show="!modelValue" class="chihuoui-switch-label close">{{inactiveText}}</view>
      </template>
    </view>
  </view>
</template>
<style lang="scss" scoped>
@import "../switch.scss";
</style>
<script lang="ts">
import { PropType, CSSProperties, toRefs,watch, computed } from "vue"
import createComponent from "@/utils/vue_component"
const { componentName, create } = createComponent("switch")
export default create({
  props: {
    modelValue: {
      type: [String, Boolean],
      default: false
    },
    activeValue: {
      type: [String,Number,Boolean],
      default: true
    },
    inactiveValue: {
      type: [String,Number,Boolean],
      default: false
    },
    loading: {
      type: Boolean,
      default: false
    },
    disable: {
      type: Boolean,
      default: false
    },
    activeColor: {
      type: String,
      default: ''
    },
    inactiveColor: {
      type: String,
      defualt: ''
    },
    activeText: {
      type: String,
      default: ""
    },
    inactiveText: {
      type: String,
      default: ""
    }
  },
  emits: ['update:modelValue','change'],
  setup(props, {emit}) {
    const isActive = computed(()=>props.modelValue === props.activeValue)
    const classes = computed(()=>{
      const prefixCls = componentName
      return {
        [prefixCls]: true,
        [isActive.value && !props.disable?'switch-open':'switch-close']: true,
        [`${prefixCls}-base`]: true
      }
    })
    const getStyles = computed(()=>{
      return {
        backgroundColor: isActive.value ? props.activeColor : props.inactiveColor
      }
    })
    let updateType = ''
    const onClick = (e:any)=>{
      if (props.loading || props.disable) return
      const value = isActive.value ? props.inactiveValue : props.activeValue
      updateType = 'click'
      emit('update:modelValue',value)
      emit('change',value,e)
    }
    watch(()=>props.modelValue,
    (v)=>{
      // if (props.disable) return
      if (updateType === 'click') {
        updateType = ''
      } else {
        emit('change',v)
      }
    })
    return {
      classes,
      getStyles,
      onClick
    }
  },
})
</script>
