// src/cmpStore/Card/react/card.tsx
//@ts-ignore
import React, { FunctionComponent } from 'react';
import Price from '@/cmpStore/Price/react';
import '../card.scss';

export interface CardProps {
  imgUrl: string;
  title: string;
  price: string;
  vipPrice: string;
  shopDesc: string;
  delivery: string;
  shopName: string;
  className: string;
  style: React.CSSProperties;
  prolistTpl: React.ReactNode;
  shopTagTpl: React.ReactNode;
  originTpl: React.ReactNode;
  footerTpl: React.ReactNode;
}
const defaultProps = {} as CardProps;
export const Card: FunctionComponent<
  Partial<CardProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const {
    children,
    className,
    style,
    imgUrl,
    title,
    price,
    vipPrice,
    shopDesc,
    delivery,
    shopName,
    shopTagTpl,
    originTpl,
    prolistTpl,
    footerTpl,
    ...rest
  } = { ...defaultProps, ...props };
  return (
    <div
      className={`chihuoui-card ${className}`}
      style={style}
    >
      <div className="chihuoui-card__left">
        <img
          src={imgUrl}
          alt=""
        />
      </div>
      <div className="chihuoui-card__right">
        <div className="chihuoui-card__right-title">{title}</div>
        {prolistTpl}
        <div className="chihuoui-card__right-price">
          {/* @ts-ignore */}
          <Price price={price} />
          {originTpl || (
            // @ts-ignore
            <Price
              className={`chihuoui-card__right-price-origin`}
              price={vipPrice}
            />
          )}
        </div>
        <div className="chihuoui-card__right-other">
          {shopTagTpl || (
            <>
              <span>{shopDesc}</span>
              <span>{delivery}</span>
            </>
          )}
        </div>
        <div className="chihuoui-card__right-shop">
          <div className="chihuoui-card__right-shop-name">{shopName}</div>
          {footerTpl}
        </div>
      </div>
    </div>
  );
};

Card.defaultProps = defaultProps;
Card.displayName = 'ChihuouiCard';

// src/cmpStore/Card/vue/card.vue
<style lang="scss" scoped>
@import "../card.scss";
</style>
<template>
  <div class="chihuoui-card">
    <div class="chihuoui-card__left">
      <img :src="imgUrl" alt="" />
    </div>
    <div class="chihuoui-card__right">
      <div class="chihuoui-card__right-title">{{ title }}</div>
      <slot name="prolist"></slot>
      <div v-if="isNeedPrice" class="chihuoui-card__right-price">
        <template v-if="isHaveSlot('price')">
          <slot name="price"></slot>
        </template>
        <Price :price="price" v-else />
        <template v-if="isHaveSlot('origin')">
          <slot name="origin"></slot>
        </template>
        <Price v-else class="chihuoui-card__right-price-origin" :price="vipPrice" />
      </div>
      <div class="chihuoui-card__right-other">
        <template v-if="isHaveSlot('shop-tag')">
          <slot name="shop-tag"></slot>
        </template>
        <template v-else>
          <span>{{ shopDesc }}</span>
          <span>{{ delivery }}</span>
        </template>
      </div>
      <div class="chihuoui-card__right-shop">
        <div class="chihuoui-card__right-shop-name">
          {{ shopName }}
        </div>
        <slot name="footer"></slot>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import { PropType, CSSProperties, toRefs, computed } from "vue"
import Price from '@/cmpStore/Price/vue'
import createComponent from "@/utils/vue_component"
const { componentName, create } = createComponent("card")
export default create({
  components: { Price },
  props: {
    imgUrl: {
      type: String,
      default: ''
    },
    title: {
      type: String,
      default: ''
    },
    price: {
      type: String,
      default: ''
    },
    vipPrice: {
      type: String,
      default: ''
    },
    shopDesc: {
      type: String,
      default: ''
    },
    delivery: {
      type: String,
      default: ''
    },
    shopName: {
      type: String,
      default: ''
    },
    isNeedPrice: {
      type: Boolean,
      default: true
    }
  },
  emits: [],
  setup(props, { emit, slots }) {
    const isHaveSlot = (slot: string) => {
      return slots[slot]
    }
    return {
      isHaveSlot
    }
  },
})
</script>
