// src/cmpStore/InfiniteLoading/vue/infiniteloading.vue
<style lang="scss" scoped>
@import "../infiniteloading.scss";
</style>
<template>
  <view :class="classes" ref="scroller">
    <div class="infinite-top" ref="infiniteTop" :style="styles">
      <div class="top-content">
        <span class="title">{{ loadingText }}</span>
      </div>
    </div>
    <view class="infinite-body">
      <slot></slot>
    </view>
    <view class="infinite-bottom">
      <template v-if="isLoadingMore">
        <view class="bottom-content">
          <span class="title">{{ loadingText }}</span>
        </view>
      </template>
      <template v-else-if="!hasMore">{{ hasNoMoreData }}</template>
    </view>
  </view>
</template>
<script lang="ts">
import { ref, PropType, CSSProperties, toRefs, computed, onMounted, reactive, onUnmounted } from "vue"
import createComponent from "@/utils/vue_component"
import { useDrag, useScroll, useGesture } from '@vueuse/gesture'
import { useSpring, useMotionProperties } from '@vueuse/motion'
import { emit } from "process"
const { componentName, create } = createComponent("infiniteloading")
export default create({
  props: {
    loadingText: {
      type: String,
      default: '加载...'
    },
    hasNoMoreData: {
      type: String,
      default: '全部加载完成~'
    },
    isRefreshOnPull: {
      type: Boolean,
      default: true
    },
    threshold: {
      type: Number,
      default: 20
    },
    hasMore: {
      type: Boolean,
      default: true
    }
  },
  emits: ['loadMore', 'refreshOnPull'],
  setup(props, { emit }) {
    const scroller = ref()
    const infiniteTop = ref()
    const parentEle = ref()
    const { motionProperties } = useMotionProperties(scroller, {
      cursor: 'grab',
      x: 0,
      y: 0
    })

    const info = reactive({
      top: 0,
      isTouching: false,
      isLoadingMore: false,
      prevScrollTop: 0,
      direction: 'down'
    })
    const topRefreshHeight = ref(0)
    const { set } = useSpring(motionProperties as any)
    const gesture = useGesture(
      {
        onDrag: ({ offset: [x, y], movement: [moveX, moveY], dragging }) => {
          info.isTouching = true
          const { scrollTop } = parentEle.value
          console.log(scrollTop);

          if (scrollTop === 0) {
            if (moveY <= topRefreshHeight.value) {
              info.top = moveY
            }
            else {
              info.top = topRefreshHeight.value
            }
          }
        },
        onDragEnd: async ({ offset: [x, y], movement: [moveX, moveY] }) => {
          info.isTouching = false
          const { scrollTop } = parentEle.value
          if (props.isRefreshOnPull && moveY >= topRefreshHeight.value && scrollTop === 0) {
            emit('refreshOnPull', () => { info.top = 0 })
          }
        },
      },
      {
        domTarget: scroller,
        eventOptions: {
          passive: false
        }
      }
    )
    const getParentEle = (el: HTMLElement) => {
      // parentEle.value = el && el.parentNode
      return el && el.parentNode
    }

    const styles = computed(() => {

      return {
        height: info.top < 0 ? 0 : `${info.top}px`,
        transition: info.isTouching ? 'height 0s cubic-bezier(0.25,0.1,0.25,1)' : 'height 0.2s cubic-bezier(0.25,0.1,0.25,1)'
      }
    })
    const classes = computed(() => {
      return {
        [componentName]: true
      }
    })
    const getInfo = () => {
      topRefreshHeight.value = ((infiniteTop.value as HTMLDivElement).firstElementChild as HTMLElement).offsetHeight + 10
    }

    const isScrollingBottom = () => {
      const { scrollHeight, scrollTop, clientHeight } = parentEle.value
      const offsetDistance = scrollHeight - scrollTop - clientHeight
      if (info.prevScrollTop < scrollTop) {
        info.direction = 'down'
      } else {
        info.direction = 'up'
      }
      info.prevScrollTop = scrollTop

      return offsetDistance <= props.threshold && info.direction === 'down'
    }

    const loadingCompleted = () => {
      info.isLoadingMore = false
    }

    const handleScroll = () => {
      requestAnimationFrame(() => {
        if (!isScrollingBottom() || !props.hasMore || info.isLoadingMore)
          return false

        info.isLoadingMore = true
        emit('loadMore', loadingCompleted)
      })
    }

    onMounted(() => {
      getInfo()
      parentEle.value = getParentEle(scroller.value as HTMLElement)
      parentEle.value.addEventListener('scroll',
        handleScroll
      )
    })

    onUnmounted(() => {
      parentEle.value.removeEventListener('scroll', handleScroll)
    })

    return {
      classes,
      scroller,
      styles,
      infiniteTop,
      ...toRefs(info),
    }
  },
})
</script>

// src/cmpStore/InfiniteLoading/react/infiniteloading.tsx
//@ts-ignore
import React, { useEffect, useState, useRef, FunctionComponent } from 'react';
import '../infiniteloading.scss';
import { useDrag, useScroll } from '@use-gesture/react';
import { useSpring, animated } from '@react-spring/web';
export interface InfiniteLoadingProps {
  containerId?: string;
  onRefresh?: () => void;
  onLoadData?: () => void;
  isRefreshAvailable?: boolean;
  threshold?: number;
}
const defaultProps = {
  containerId: '',
  isRefreshAvailable: true,
  threshold: 20,
} as InfiniteLoadingProps;
export const InfiniteLoading: FunctionComponent<
  Partial<InfiniteLoadingProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const {
    children,
    threshold,
    containerId,
    isRefreshAvailable,
    onRefresh,
    onLoadData,
  } = {
    ...defaultProps,
    ...props,
  };
  const scroller = useRef<HTMLDivElement>(null);
  const top = useRef(0);
  const prevOffsetY = useRef(0);
  const infiniteTop = useRef<HTMLDivElement>(null);
  const topHeight = useRef(0);
  const isTouching = useRef(false);
  const topRefreshHeight = useRef(0);
  const [isLoadingData, setIsLoadingData] = useState(false);
  const styles = () => {
    return {
      height: top.current < 0 ? 0 : `${top.current}px`,
      transition: isTouching.current
        ? 'height 0 cubic-bezier(0.25,0.1,0.25,1)'
        : 'height .2s cubic-bezier(0.25,0.1,0.25,1)',
    };
  };
  const getParentEle = (el: HTMLElement) => {
    return containerId
      ? document.querySelector(`#${containerId}`)
      : el && el.parentNode;
  };
  const scrollY = useRef(0);
  const drag = useDrag(
    async ({
      dragging,
      movement: [moveX, moveY],
      offset: [offsetX, offsetY],
    }) => {
      const { scrollHeight, clientHeight } = scroller.current as HTMLElement;

      if (isRefreshAvailable) {
        const infiniteTopEl = infiniteTop.current as HTMLDivElement;

        if (dragging) {
          if (moveY < topRefreshHeight.current && !isTouching.current) {
            if (offsetY > 0) infiniteTopEl.style.height = `${moveY}px`;
          } else {
            if (offsetY > 0)
              infiniteTopEl.style.height = `${topRefreshHeight.current}px`;
          }
          top.current = moveY;
        } else {
          if (top.current >= topRefreshHeight.current && offsetY > 0) {
            onRefresh && (await onRefresh());
          }
          infiniteTopEl.style.height = '0px';
          top.current = 0;
          isTouching.current = false;
        }
      }

      if (offsetY < 0) {
        if (
          Math.abs(offsetY) <=
          scrollHeight - clientHeight - (threshold as number)
        ) {
          scrollY.current = offsetY;
          (
            scroller.current as HTMLDivElement
          ).style.transform = `translate3d(0, ${scrollY.current}px,0)`;
        } else {
          if (!isLoadingData && !dragging) {
            setIsLoadingData(true);
            (
              scroller.current as HTMLDivElement
            ).style.transform = `translate3d(0, ${
              -scrollHeight + clientHeight - 30
            }px,0)`;
            onLoadData && (await onLoadData());
            console.log('loaded data');

            setIsLoadingData(false);
          }
        }
      }
    },
    { delay: true }
  );
  useEffect(() => {
    const parentEle = getParentEle(
      scroller.current as HTMLElement
    ) as HTMLElement;
    parentEle.style.overflow = 'hidden';
    topHeight.current = (
      (infiniteTop.current as HTMLDivElement).firstElementChild as HTMLElement
    ).offsetHeight;
    topRefreshHeight.current = topHeight.current + 10;
  }, [infiniteTop.current?.firstElementChild]);

  return (
    <div className="chihuoui-infiniteloading" ref={scroller} {...drag()}>
      <div className="infinite-top" style={styles()} ref={infiniteTop}>
        <div className="top-content">
          <span className="title">下拉加载</span>
        </div>
      </div>
      <div className="infinite-body">{children}</div>
      <div className="infinite-bottom">
        {isLoadingData ? (
          <div className="bottom-content">
            <span className="title">加载...</span>
          </div>
        ) : (
          <div></div>
        )}
      </div>
    </div>
  );
};

InfiniteLoading.defaultProps = defaultProps;
InfiniteLoading.displayName = 'ChihuouiInfiniteLoading';
