// src/cmpStore/Skeleton/react/demo.tsx
import React, { useRef } from 'react';
import { Skeleton } from './skeleton';
const SkeletonDemo = () => {
  const loading = useRef(false);
  return (
    <>
      <div className="demo">
        <h2>基础用法</h2>
        <Skeleton
          row="6"
          animated
          round
          loading={loading.current}
          height="20px"
          width="300px"
        ></Skeleton>
      </div>
    </>
  );
};

export default SkeletonDemo;

// src/cmpStore/Skeleton/vue/demo.vue
<style lang="scss" scoped>
@import "../skeleton.scss";
</style>
<template>
	<Skeleton row="6" animated round :loading="loading" height="20px" width="300px"></Skeleton>
</template>
<script lang="ts">
import { ref, onMounted } from 'vue'
import Skeleton from './skeleton.vue'
export default {
	props: {},
	emits: [],
	components: { Skeleton },
	setup(props) {
		const loading = ref(false)
		onMounted(() => {
			// setTimeout(() => {
			// 	loading.value = false
			// }, 3000)
		})
		return {
			loading
		}
	}
}
</script>
