// src/cmpStore/Skeleton/react/skeleton.tsx
//@ts-ignore
import React, { FunctionComponent } from 'react';
import '../skeleton.scss';

export interface SkeletonProps {
  round?: boolean;
  animated?: boolean;
  width?: string;
  height?: string;
  loading?: boolean;
  row: number;
  title: boolean;
  children?: React.ReactNode;
}
const defaultProps = {
  round: false,
  animated: false,
  loading: false,
  height: '20px',
  width: '100px',
  title: false,
  row: 1,
} as SkeletonProps;
export const Skeleton: FunctionComponent<Partial<SkeletonProps>> = (props) => {
  const { loading, animated, round, height, width, title, row, children } = {
    ...defaultProps,
    ...props,
  };
  const getCls = (classname: string) => {
    return `
      ${classname}
      ${classname}--round
    `;
    // [classname]: true,
    // [`${classname}--round`]: round,
  };
  const styles = () => {};
  const data = (rowLen: number) => {
    return Array.from({ length: rowLen }, (v, i) => i);
  };
  return (
    <>
      {loading ? (
        <div>{children}</div>
      ) : (
        <div className={getCls('skeleton')}>
          {animated && <div className="skeleton-animation" />}
          <div className="content">
            <div
              className="content-line"
              style={{ width }}
            >
              {title && <div className="title" />}
              {data(row).map((item, index) => {
                return (
                  <div
                    key={index}
                    className={getCls('blockLine')}
                    style={{ height }}
                  />
                );
              })}
            </div>
          </div>
        </div>
      )}
    </>
  );
};

Skeleton.defaultProps = defaultProps;
Skeleton.displayName = 'ChihuouiSkeleton';

// src/cmpStore/Skeleton/vue/skeleton.vue
<style lang="scss" scoped>
@import "../skeleton.scss";
</style>
<template>
  <view v-if="loading">
    <slot></slot>
  </view>
  <view v-else class="skeleton">
    <view class="skeleton-animation" v-if="animated"></view>
    <view class="content">
      <view class="content-line" :style="{ width }">
        <view v-if="title" :class="getCls('blockTitle')" :style="{ height }"></view>
        <view v-for="_ in Number(row)" :key="Math.random()" :class="getCls('blockLine')" :style="{ height }"></view>
      </view>
    </view>
  </view>
</template>
<script lang="ts">
import { PropType, CSSProperties, toRefs, computed } from "vue"
import createComponent from "@/utils/vue_component"
const { componentName, create } = createComponent("skeleton")
export default create({
  props: {
    width: {
      type: String,
      default: '100px'
    },
    height: {
      type: String,
      default: '100px'
    },
    animated: {
      type: Boolean,
      default: false
    },
    loading: {
      type: Boolean,
      default: false
    },
    row: {
      type: String,
      default: '1'
    },
    title: {
      type: Boolean,
      default: false
    },
    round: {
      type: Boolean,
      default: false
    }
  },
  emits: [],
  setup(props) {
    const { round, row } = toRefs(props)
    const styles = () => {
      const style: CSSProperties = {}
      return {
        width: '50px',
        height: '50px'
      }
    }
    const getCls = (prefix: string) => {
      return {
        [prefix]: true,
        [`${prefix}--round`]: round.value
      }
    }

    return {
      styles,
      getCls
    }
  },
})
</script>
